### ISSUE TITLE
Setup asks for Visual C++ and won´t let me to complete setup (v. Pre-alpha 7)

### ISSUE THREAD

**Issue by GatoVuelta** [Komodroid/The.Ring-2D-Battle-Royale#1]

**Comment by Moondev0607** [comment]
If the SETUP asks your for "Visual C++ Redistributable 2010 or later", and already have one newer installed or similar, and won´t let you to continue the setup, please do the following:

1.   Click on "Accept"

![image](https://user-images.githubusercontent.com/79285823/111207699-f1e7fa80-8597-11eb-9541-65f52e89e802.png)

2. If you are using Windows 8 or newer, it will appear another popup, click "Cancel" on that.

![image](https://user-images.githubusercontent.com/79285823/111207726-f8767200-8597-11eb-8697-e67c2dec0b63.png)

3. Done! You can continue the setup as usual.

![image](https://user-images.githubusercontent.com/79285823/111207876-252a8980-8598-11eb-9277-409fd5329463.png)

**Comment by DevCatto** [comment]
Nice Solve! lol Catflip thanks
